### ISSUE TITLE
Discord link is expired

### ISSUE THREAD

**Issue by Apep-the-snek** [LiquidZulu/liquidzulu.github.io#105]
Get a permanent link if you can, or just not have it advertised.

**Comment by Lord-Valen** [comment]
The server is not expected to be open until after election season.

**Comment by LiquidZulu** [comment]
There is perhaps something to be said about removing the link from the footer until then though, so I will keep the issue open for now.

**Comment by LiquidZulu** [comment]
resolved by [#](https://github.com/LiquidZulu/liquidzulu.github.io/commit/e747e077ffcaf0748fa6af292ab9a245f012c67f)
