### ISSUE TITLE
You claim you want to integrate all of philosophy, yet...

### ISSUE THREAD

**Issue by Apep-the-snek** [LiquidZulu/liquidzulu.github.io#106]
You do not cover Philosophical veganism. Look into the NTT (Name The Trait). great resource for this would be https://www.the-nutrivore.com/ he likes using predicate calculus and such (however there are many things to disagree with him on like on how he want to change the animal world by caging and feeding mainly odd-order predators vegan food). Personally i think philosophical veganism is 100% compatible with Anarcho-capitalism viewed through the right lens, viewing animals as having the same rights as us (yes, predators do violate other species' life).

yes i have adopted this philosophy to my real life, and i'm very okay, not that it matters to me, being ethical and moral is more important to me than being healthy.

I originally wanted to debate you on discord, but since that link is broken, i just thought this was a better way to interact. also it would be epic to have a respectful debate in this thread about anarcho-capitalist-veganism and philosophy.

**Comment by LiquidZulu** [comment]
Please move this issue [here](https://github.com/LiquidZulu/brain/issues). (This repo is for the website more broadly, that one is for the brain specifically, I should probably make a contribution guide or something to clear this up).

I am currently still going over the epistemology, I will cover NTT when I get to law, you can debate me on it now if you want though, my discord username is `liquidzulu`.

**Comment by Apep-the-snek** [comment]
> I am currently still going over the epistemology, I will cover NTT when I get to law, you can debate me on it now if you want though, my discord username is `liquidzulu`.

I sent a friend request with the name `unitetruth`, and i have a message prepared (can't send because we have no servers in common).
