### ISSUE TITLE
Highlighted sections off-screen

### ISSUE THREAD

**Issue by Bigtruck2** [LiquidZulu/liquidzulu.github.io#129]
When scrolling up or down on a page, the highlighted section goes off-screen.
![Screenshot_20240416_232823](https://github.com/LiquidZulu/liquidzulu.github.io/assets/86583611/a18e67de-56a4-4d56-9227-3cb4dd166b98)
Here is how I fixed it:
https://github.com/LiquidZulu/liquidzulu.github.io/compare/source...Bigtruck2:liquidzulu.github.io:section

**Comment by LiquidZulu** [comment]
Ok, so just so I'm understanding---this would make it such that if you click a TOC item the TOC will actually bother scrolling to it as if you had scrolled to that heading in the main body, right?

**Comment by Bigtruck2** [comment]
This would make it so when a new TOC item is highlighted, the TOC would scroll up or down to that item if it is not on screen. This occurs both when a toc item is clicked and when a user scrolls on the main page to a different heading. It only affects the scroll of the TOC not the main body.

**Comment by LiquidZulu** [comment]
Does it allow the person to use the TOC to scroll down? Like, if the first item is highlighted, could I scroll past it on the TOC to see what other sections are there?

**Comment by LiquidZulu** [comment]
Ah, I see the behaviour now---tested it on local. Looks good. Does smooth scrolling break it on chromium (I seem to recall chromium having issues with smooth scrolling, and I am not seeing smooth scrolling).

**Comment by LiquidZulu** [comment]
seemed to work on local, but now it isn't---I do not know why

**Comment by Bigtruck2** [comment]
I've added smooth scrolling and didn't see any problems on Chrome https://github.com/Bigtruck2/liquidzulu.github.io/commit/b02ebea2dfa816d4df867246cb2491ca6e7e2afb

**Comment by LiquidZulu** [comment]
Might have been some caching issue---I think it is working now

**Comment by LiquidZulu** [comment]
ah, I think https://github.com/LiquidZulu/liquidzulu.github.io/pull/130/commits/d0961e71ddd06c8359a66968da0d1517a89b9f5b was working, but not the newer one

**Comment by LiquidZulu** [comment]
at least on librewolf, will try to confirm

**Comment by LiquidZulu** [comment]
hm, no seems to work now, but only on local. Are you seeing the proper behaviour on the live site?

**Comment by Bigtruck2** [comment]
It works on local but not on the live site.

**Comment by LiquidZulu** [comment]
hm, maybe the build fucked up in some way that it looked like it succeeded---will try build again

**Comment by LiquidZulu** [comment]
Yep, redeploy seems to have worked---I bet it is something to do with dependabot getting pissed off.
