### ISSUE TITLE
backliks broken

### ISSUE THREAD

**Issue by LiquidZulu** [LiquidZulu/liquidzulu.github.io#92]
for some reason the backlinks no longer show up.

**Comment by Lord-Valen** [comment]
They seem to work for me. https://liquidzulu.github.io/brain/note/opar/ backlinks to https://liquidzulu.github.io/brain/note/the-attack-on-the-senses-by-eddingtons-two-tables/, and that is reflected in the backlinks section of the OPAR note.

**Comment by LiquidZulu** [comment]
Strange, https://liquidzulu.github.io/brain/note/entity/ should have a backlink pointing to https://liquidzulu.github.io/brain/note/examples-of-entities/ that is a slightly more odd bug

**Comment by Lord-Valen** [comment]
That's weird. Are the backlinks just taken from Obsidian's DB? Maybe it's out of date?

**Comment by Lord-Valen** [comment]
I looked at it a little more closely. Can you bisect? I suspect it works before you started using getSlug.

**Comment by LiquidZulu** [comment]
Backlinks are computed [here](https://github.com/LiquidZulu/liquidzulu.github.io/blob/8ccc6e08e99577fae950b560c16159f200806dd0/src/util/wikilinks.ts#L79), I'll see about de-bugging this

**Comment by LiquidZulu** [comment]
![image](https://github.com/LiquidZulu/liquidzulu.github.io/assets/34405159/4d8230eb-515e-4ac6-9e3d-8e7fdbef919d)
interesting

**Comment by LiquidZulu** [comment]
ah, I bet you its to do with aliases

**Comment by LiquidZulu** [comment]
It is indeed to do with aliases, need to work out why, it could be when the same note is aliased from multiple places within the same note, as is the case with https://liquidzulu.github.io/brain/note/the-invalidity-of-the-senses-implies-the-invalidity-of-knowledge/ linking to https://liquidzulu.github.io/brain/note/validation twice

**Comment by LiquidZulu** [comment]
ah, I am computing it from the entry body, that will be the problem
![image](https://github.com/LiquidZulu/liquidzulu.github.io/assets/34405159/092c1e3a-e492-4274-8dc2-c7d4cf2bdf38)

**Comment by LiquidZulu** [comment]
![image](https://github.com/LiquidZulu/liquidzulu.github.io/assets/34405159/384166cb-8fbe-400d-84fc-b00bf4010f63)
ladies and gentlemen, we got him

**Comment by LiquidZulu** [comment]
Yes, getting the slug now strips it of the "|", so it needs to be pre-split

**Comment by Lord-Valen** [comment]
So you need to split the string into an array by `|` and iterate over them?

**Comment by LiquidZulu** [comment]
I just need to split by `|` to get the actual link of the wikilink, this needs to happen prior to computing the slug, seems to work when I do it first

**Comment by LiquidZulu** [comment]
a wikilink has `[[where-you-are-linking-to|friendly name for it]]`

**Comment by Lord-Valen** [comment]
I see. So you split and take the head of the wikilink.

**Comment by LiquidZulu** [comment]
yeah
